### ISSUE TITLE
resize twitter, facebook, and all red buttons to 524x55 in landscape view and center

### ISSUE THREAD

**Issue by alexctolbert** [Grablr/Grablr-FE#5]
Twitter, Facebook, and all red buttons need to be resized to 524x55 and centered for iPad in landscape view.

I tried this through the storyboard editor but the format changed the centering for buttons in portrait view.

**Comment by bengottlieb** [comment]
LOE: 1 hr

**Comment by alexctolbert** [comment]
This was resolved
