### ISSUE TITLE
change nav menu titles

### ISSUE THREAD

**Issue by alexctolbert** [Grablr/Grablr-FE#6]
Edit "Today's Sale" to "Weekly Overview"
Remove "Manage Next Sale" and add "Today's Orders"

Today's Orders will need to route the user to the order screen for today. This is currently done by going to Order History, and picking the current day.

**Comment by bengottlieb** [comment]
LOE: 1-3 hrs [second line is a little ambiguous]

**Comment by alexctolbert** [comment]
This was completed
